### ISSUE TITLE
1.20.6 only

### ISSUE THREAD

**Issue by SavageTheUnicorn** [ryderbelserion/Pl3xMapExtras#4]
### Plugin Version

latest

### Server Version

1.20.1

### Server Platform

Paper

### Describe the bug

The plugin will not load as it says its only for 1.20.6

### Steps to reproduce

Simply upload the plugin to a 1.20.4 paper server, i saw that 1.20.4 was in the bugs.yml though.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported.

**Comment by ryderbelserion** [comment]
That is not a bug, that is intended for it to only boot on 1.20.6.

**Comment by SavageTheUnicorn** [comment]
Ah. I was hoping to use this on my 1.20.4 server as some of my plugins dont support 1.20.6, I tried. Thanks for the information.
